export const data = [
    {
        id: 1,
        productCode: 'GLA-001',
        title: 'Glasses super beautiful for men and women. Have all color and size for choosing 1',
        price: 100,
        discount: 10,
        thumbnail: '/data-image/eg-01.jpg',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        stockQuantity: 7900,
        soldQuantity: 10700,
        category_id: 1,
    },
    {
        id: 2,
        productCode: 'GLA-001',
        title: 'Glasses super beautiful for men and women. Have all color and size for choosing 2',
        price: 200,
        discount: 0,
        thumbnail: '/data-image/eg-02.jpg',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        stockQuantity: 7900,
        soldQuantity: 10700,
        category_id: 1,
    },
    {
        id: 3,
        productCode: 'GLA-001',
        title: 'Glasses super beautiful for men and women. Have all color and size for choosing 3',
        price: 300,
        discount: 30,
        thumbnail: '/data-image/eg-03.jpg',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        stockQuantity: 7900,
        soldQuantity: 10700,
        category_id: 2,
    },
    {
        id: 4,
        productCode: 'GLA-001',
        title: 'Glasses super beautiful for men and women. Have all color and size for choosing 4',
        price: 400,
        discount: 40,
        thumbnail: '/data-image/eg-04.jpg',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        stockQuantity: 7900,
        soldQuantity: 10700,
        category_id: 2,
    },
    {
        id: 5,
        productCode: 'GLA-001',
        title: 'Glasses super beautiful for men and women. Have all color and size for choosing 5',
        price: 500,
        discount: 0,
        thumbnail: '/data-image/eg-05.jpg',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        stockQuantity: 7900,
        soldQuantity: 10700,
        category_id: 3,
    },
    {
        id: 6,
        productCode: 'GLA-001',
        title: 'Glasses super beautiful for men and women. Have all color and size for choosing 6',
        price: 600,
        discount: 60,
        thumbnail: '/data-image/eg-01.jpg',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        stockQuantity: 7900,
        soldQuantity: 10700,
        category_id: 3,
    },
    {
        id: 7,
        productCode: 'GLA-001',
        title: 'Glasses super beautiful for men and women. Have all color and size for choosing 7',
        price: 700,
        discount: 10,
        thumbnail: '/data-image/eg-01.jpg',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        stockQuantity: 7900,
        soldQuantity: 10700,
        category_id: 1,
    },

    {
        id: 8,
        productCode: 'GLA-001',
        title: 'Glasses super beautiful for men and women. Have all color and size for choosing 8',
        price: 800,
        discount: 20,
        thumbnail: '/data-image/eg-01.jpg',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        stockQuantity: 7900,
        soldQuantity: 10700,
        category_id: 1,
    },
    {
        id: 9,
        productCode: 'GLA-001',
        title: 'Glasses super beautiful for men and women. Have all color and size for choosing 9',
        price: 900,
        discount: 30,
        thumbnail: '/data-image/eg-01.jpg',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        stockQuantity: 7900,
        soldQuantity: 10700,
        category_id: 2,
    },
    {
        id: 10,
        productCode: 'GLA-001',
        title: 'Glasses super beautiful for men and women. Have all color and size for choosing 10',
        price: 1000,
        discount: 10,
        thumbnail: '/data-image/eg-01.jpg',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        stockQuantity: 7900,
        soldQuantity: 10700,
        category_id: 2,
    },

    {
        id: 11,
        productCode: 'GLA-001',
        title: 'Glasses super beautiful for men and women. Have all color and size for choosing 11',
        price: 1100,
        discount: 10,
        thumbnail: '/data-image/eg-01.jpg',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        stockQuantity: 7900,
        soldQuantity: 10700,
        category_id: 3,
    },

    {
        id: 12,
        productCode: 'GLA-001',
        title: 'Glasses super beautiful for men and women. Have all color and size for choosing 12',
        price: 1200,
        discount: 20,
        thumbnail: '/data-image/eg-01.jpg',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        stockQuantity: 7900,
        soldQuantity: 10700,
        category_id: 3,
    },

    {
        id: 13,
        productCode: 'GLA-001',
        title: 'Glasses super beautiful for men and women. Have all color and size for choosing 13',
        price: 1300,
        discount: 0,
        thumbnail: '/data-image/eg-01.jpg',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        stockQuantity: 7900,
        soldQuantity: 10700,
        category_id: 1,
    },

    {
        id: 14,
        productCode: 'GLA-001',
        title: 'Glasses super beautiful for men and women. Have all color and size for choosing 14',
        price: 1400,
        discount: 10,
        thumbnail: '/data-image/eg-01.jpg',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        stockQuantity: 7900,
        soldQuantity: 10700,
        category_id: 1,
    },

    {
        id: 15,
        productCode: 'GLA-001',
        title: 'Glasses super beautiful for men and women. Have all color and size for choosing 15',
        price: 1500,
        discount: 0,
        thumbnail: '/data-image/eg-01.jpg',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        stockQuantity: 7900,
        soldQuantity: 10700,
        category_id: 2,
    },

    {
        id: 16,
        productCode: 'GLA-001',
        title: 'Glasses super beautiful for men and women. Have all color and size for choosing 16',
        price: 1600,
        discount: 10,
        thumbnail: '/data-image/eg-01.jpg',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        stockQuantity: 7900,
        soldQuantity: 10700,
        category_id: 2,
    },

    {
        id: 17,
        productCode: 'GLA-001',
        title: 'Glasses super beautiful for men and women. Have all color and size for choosing 17',
        price: 1700,
        discount: 0,
        thumbnail: '/data-image/eg-01.jpg',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        stockQuantity: 7900,
        soldQuantity: 10700,
        category_id: 3,
    },

    {
        id: 18,
        productCode: 'GLA-001',
        title: 'Glasses super beautiful for men and women. Have all color and size for choosing 18',
        price: 1800,
        discount: 10,
        thumbnail: '/data-image/eg-01.jpg',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        stockQuantity: 7900,
        soldQuantity: 10700,
        category_id: 3,
    },

    {
        id: 19,
        productCode: 'GLA-001',
        title: 'Glasses super beautiful for men and women. Have all color and size for choosing 19',
        price: 1900,
        discount: 10,
        thumbnail: '/data-image/eg-01.jpg',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        stockQuantity: 7900,
        soldQuantity: 10700,
        category_id: 1,
    },

    {
        id: 20,
        productCode: 'GLA-001',
        title: 'Glasses super beautiful for men and women. Have all color and size for choosing 20',
        price: 2000,
        discount: 10,
        thumbnail: '/data-image/eg-01.jpg',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        stockQuantity: 7900,
        soldQuantity: 10700,
        category_id: 1,
    },
];
