export const data = [
    {
        id: 1,
        category_id: 1,
        title: 'Glasses super beautiful for men and women. Have all color and size for choosing 1',
        price: 100,
        discount: 10,
        thumbnail: 'https://placehold.co/10x10',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    },
    {
        id: 2,
        category_id: 1,
        title: 'Glasses super beautiful for men and women. Have all color and size for choosing 2',
        price: 200,
        discount: 0,
        thumbnail: 'https://placehold.co/10x10',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    },
    {
        id: 3,
        category_id: 2,
        title: 'Glasses super beautiful for men and women. Have all color and size for choosing 3',
        price: 300,
        discount: 30,
        thumbnail: 'https://placehold.co/10x10',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    },
    {
        id: 4,
        category_id: 2,
        title: 'Glasses super beautiful for men and women. Have all color and size for choosing 4',
        price: 400,
        discount: 40,
        thumbnail: 'https://placehold.co/10x10',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    },
    {
        id: 5,
        category_id: 3,
        title: 'Glasses super beautiful for men and women. Have all color and size for choosing 5',
        price: 500,
        discount: 0,
        thumbnail: 'https://placehold.co/10x10',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    },
    {
        id: 6,
        category_id: 3,
        title: 'Glasses super beautiful for men and women. Have all color and size for choosing 6',
        price: 600,
        discount: 60,
        thumbnail: 'https://placehold.co/10x10',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    },
    {
        id: 7,
        category_id: 4,
        title: 'Glasses super beautiful for men and women. Have all color and size for choosing 7',
        price: 700,
        discount: 10,
        thumbnail: 'https://placehold.co/10x10',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    },

    {
        id: 8,
        category_id: 4,
        title: 'Glasses super beautiful for men and women. Have all color and size for choosing 8',
        price: 800,
        discount: 20,
        thumbnail: 'https://placehold.co/10x10',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    },
    {
        id: 9,
        category_id: 5,
        title: 'Glasses super beautiful for men and women. Have all color and size for choosing 9',
        price: 900,
        discount: 30,
        thumbnail: 'https://placehold.co/10x10',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    },
    {
        id: 10,
        category_id: 5,
        title: 'Glasses super beautiful for men and women. Have all color and size for choosing 10',
        price: 1000,
        discount: 10,
        thumbnail: 'https://placehold.co/10x10',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    },

    {
        id: 11,
        category_id: 6,
        title: 'Glasses super beautiful for men and women. Have all color and size for choosing 11',
        price: 1100,
        discount: 10,
        thumbnail: 'https://placehold.co/10x10',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    },

    {
        id: 12,
        category_id: 6,
        title: 'Glasses super beautiful for men and women. Have all color and size for choosing 12',
        price: 1200,
        discount: 20,
        thumbnail: 'https://placehold.co/10x10',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    },

    {
        id: 13,
        category_id: 7,
        title: 'Glasses super beautiful for men and women. Have all color and size for choosing 13',
        price: 1300,
        discount: 0,
        thumbnail: 'https://placehold.co/10x10',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    },

    {
        id: 14,
        category_id: 7,
        title: 'Glasses super beautiful for men and women. Have all color and size for choosing 14',
        price: 1400,
        discount: 10,
        thumbnail: 'https://placehold.co/10x10',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    },

    {
        id: 15,
        category_id: 8,
        title: 'Glasses super beautiful for men and women. Have all color and size for choosing 15',
        price: 1500,
        discount: 0,
        thumbnail: 'https://placehold.co/10x10',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    },

    {
        id: 16,
        category_id: 8,
        title: 'Glasses super beautiful for men and women. Have all color and size for choosing 16',
        price: 1600,
        discount: 10,
        thumbnail: 'https://placehold.co/10x10',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    },

    {
        id: 17,
        category_id: 9,
        title: 'Glasses super beautiful for men and women. Have all color and size for choosing 17',
        price: 1700,
        discount: 0,
        thumbnail: 'https://placehold.co/10x10',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    },

    {
        id: 18,
        category_id: 9,
        title: 'Glasses super beautiful for men and women. Have all color and size for choosing 18',
        price: 1800,
        discount: 10,
        thumbnail: 'https://placehold.co/10x10',
        description:
            'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam auctor, nunc nec ultricies ultricies, nun',
    },

    {
        id: 19,
        category_id: 10,
        title: 'Glasses super beautiful for men and women. Have all color and size for choosing 19',
        price: 1900,
        discount: 10,
        thumbnail: 'https://placehold.co/10x10',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    },

    {
        id: 20,
        category_id: 10,
        title: 'Glasses super beautiful for men and women. Have all color and size for choosing 20',
        price: 2000,
        discount: 10,
        thumbnail: 'https://placehold.co/10x10',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
    },
];
