spring.application.name=eyeglass
#spring.security.customer.name=${SECURITY_USER_NAME:admin}
#spring.security.customer.password=${SECURITY_USER_PASSWORD:admin}
## Logging configuration
logging.level.org.springframework.security=${SPRING_SECURITY_LOG_LEVEL:TRACE}
logging.pattern.console=${LOG_PATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}
# DataSource configuration
spring.datasource.url=jdbc:mysql://localhost:3306/EyeGlassShop
spring.datasource.username=root
spring.datasource.password=Hau643@#
## JPA/Hibernate configuration
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
