spring:
  application:
    name: ${SPRING_APP_NAME:eyeglass}
  datasource:
    url: jdbc:mysql://avnadmin:AVNS_7tuSVyFY8tOOOQ0rCss@mysql-eyeglass-nln-ct46605.h.aivencloud.com:28819/defaultdb?ssl-mode=REQUIRED
    username: ${DATABASE_USERNAME:avnadmin}
    password: ${DATABASE_PASSWORD:AVNS_7tuSVyFY8tOOOQ0rCss}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: ${JPA_SHOW_SQL:true}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  web:
    resources:
      add-mappings: false

logging:
  level:
    org.springframework.security: ${SPRING_SECURITY_LOG_LEVEL:TRACE}
  pattern:
    console: ${LOG_PATTERN_CONSOLE:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n}

server:
  servlet:
    session:
      timeout: ${SESSION_TIMEOUT:20m}

jwt:
  rsa-private-key: classpath:certs/privateKey.pem
  rsa-public-key: classpath:certs/publicKey.pem
